# @package _global_

paths:
    nadir: /Odyssey/public/altimetry_traces/processed_2023_global_4/gridded/gridded_input.nc

domain: ???

trainer:
  _target_: pytorch_lightning.Trainer
  inference_mode: False
  gradient_clip_val: 0.5
  accelerator: gpu
  devices: 1
  limit_train_batches: 250.
  limit_val_batches: 30.
  accumulate_grad_batches: 16
  logger: 
    _target_: pytorch_lightning.loggers.CSVLogger
    save_dir: ${hydra:runtime.output_dir}
    name: ${hydra:runtime.choices.xp}
    version: ''
  max_epochs: 5
  callbacks:
    - _target_: src.versioning_cb.VersioningCallback
    - _target_: pytorch_lightning.callbacks.LearningRateMonitor
    - _target_: pytorch_lightning.callbacks.ModelCheckpoint
      monitor: val_mse
      save_top_k: 3
      save_last: True
      filename: 'ssh_spde_frcst2_6nadirs_{val_mse:.5f}-{epoch:03d}.ckpt'

datamodule:
  _target_: src.data_notebook_fast.BaseDataModule
  input_da: 
    _target_: contrib.IMT.SPDE.load_data.open_l3_data
    path: ${paths.nadir}
    domain: ${domain.train}
  domains:
    train:
      time: {_target_: builtins.slice, _args_: ['2023-01-01', '2023-10-17']}
    val: 
      time: {_target_: builtins.slice, _args_: ['2023-10-18', '2023-11-24']}
    test:
      time:
        - {_target_: builtins.slice, _args_: ['2022-12-07', '2023-01-06']}
        - {_target_: builtins.slice, _args_: ['2022-12-14', '2023-01-13']}
        - {_target_: builtins.slice, _args_: ['2022-12-21', '2023-01-20']}
        - {_target_: builtins.slice, _args_: ['2022-12-28', '2023-01-27']}
        - {_target_: builtins.slice, _args_: ['2023-01-04', '2023-02-03']}
        - {_target_: builtins.slice, _args_: ['2023-01-11', '2023-02-10']}
        - {_target_: builtins.slice, _args_: ['2023-01-18', '2023-02-17']}
        - {_target_: builtins.slice, _args_: ['2023-01-25', '2023-02-24']}
        - {_target_: builtins.slice, _args_: ['2023-02-01', '2023-03-03']}
        - {_target_: builtins.slice, _args_: ['2023-02-08', '2023-03-10']}
        - {_target_: builtins.slice, _args_: ['2023-02-15', '2023-03-17']}
        - {_target_: builtins.slice, _args_: ['2023-02-22', '2023-03-24']}
        - {_target_: builtins.slice, _args_: ['2023-03-01', '2023-03-31']}
        - {_target_: builtins.slice, _args_: ['2023-03-08', '2023-04-07']}
        - {_target_: builtins.slice, _args_: ['2023-03-15', '2023-04-14']}
        - {_target_: builtins.slice, _args_: ['2023-03-22', '2023-04-21']}
        - {_target_: builtins.slice, _args_: ['2023-03-29', '2023-04-28']}
        - {_target_: builtins.slice, _args_: ['2023-04-05', '2023-05-05']}
        - {_target_: builtins.slice, _args_: ['2023-04-12', '2023-05-12']}
        - {_target_: builtins.slice, _args_: ['2023-04-19', '2023-05-19']}
        - {_target_: builtins.slice, _args_: ['2023-04-26', '2023-05-26']}
        - {_target_: builtins.slice, _args_: ['2023-05-03', '2023-06-02']}
        - {_target_: builtins.slice, _args_: ['2023-05-10', '2023-06-09']}
        - {_target_: builtins.slice, _args_: ['2023-05-17', '2023-06-16']}
        - {_target_: builtins.slice, _args_: ['2023-05-24', '2023-06-23']}
        - {_target_: builtins.slice, _args_: ['2023-05-31', '2023-06-30']}
        - {_target_: builtins.slice, _args_: ['2023-06-07', '2023-07-07']}
        - {_target_: builtins.slice, _args_: ['2023-06-14', '2023-07-14']}
        - {_target_: builtins.slice, _args_: ['2023-06-21', '2023-07-21']}
        - {_target_: builtins.slice, _args_: ['2023-06-28', '2023-07-28']}
        - {_target_: builtins.slice, _args_: ['2023-07-05', '2023-08-04']}
        - {_target_: builtins.slice, _args_: ['2023-07-12', '2023-08-11']}
        - {_target_: builtins.slice, _args_: ['2023-07-19', '2023-08-18']}
        - {_target_: builtins.slice, _args_: ['2023-07-26', '2023-08-25']}
        - {_target_: builtins.slice, _args_: ['2023-08-02', '2023-09-01']}
        - {_target_: builtins.slice, _args_: ['2023-08-09', '2023-09-08']}
        - {_target_: builtins.slice, _args_: ['2023-08-16', '2023-09-15']}
        - {_target_: builtins.slice, _args_: ['2023-08-23', '2023-09-22']}
        - {_target_: builtins.slice, _args_: ['2023-08-30', '2023-09-29']}
        - {_target_: builtins.slice, _args_: ['2023-09-06', '2023-10-06']}
        - {_target_: builtins.slice, _args_: ['2023-09-13', '2023-10-13']}
        - {_target_: builtins.slice, _args_: ['2023-09-20', '2023-10-20']}
        - {_target_: builtins.slice, _args_: ['2023-09-27', '2023-10-27']}
        - {_target_: builtins.slice, _args_: ['2023-10-04', '2023-11-03']}
        - {_target_: builtins.slice, _args_: ['2023-10-11', '2023-11-10']}
        - {_target_: builtins.slice, _args_: ['2023-10-18', '2023-11-17']}
        - {_target_: builtins.slice, _args_: ['2023-10-25', '2023-11-24']}
        - {_target_: builtins.slice, _args_: ['2023-11-01', '2023-12-01']}
        - {_target_: builtins.slice, _args_: ['2023-11-08', '2023-12-08']}
        - {_target_: builtins.slice, _args_: ['2023-11-15', '2023-12-15']}
        - {_target_: builtins.slice, _args_: ['2023-11-22', '2023-12-22']}
        - {_target_: builtins.slice, _args_: ['2023-11-29', '2023-12-29']} 
  xrds_kw:
    patch_dims: { time: 29, lat: 120, lon: 120}
    strides: { time: 1, lat: 100, lon: 100}
    domain_limits: ${domain.train}
  dl_kw: {batch_size: 2, num_workers: 1}
  aug_kw:
    aug_factor: 2
    aug_only: True
  #resize_factor: 2
  frcst_lead: 2
  norm_stats:
    - -0.13265216
    - 0.72527287

model:
  _target_: contrib.IMT.SPDE.lit_model_spde_winit.Lit4dVarNet
  frcst_lead: ${datamodule.frcst_lead}
  persist_rw: False
  epoch_start_opt2: 3
  opt_fn:
    _target_: src.utils.cosanneal_spde_lr_adam_winit
    _partial_: true
    lr: 1e-3
    T_max: ${trainer.max_epochs}
  rec_weight:
    _target_: src.utils.get_last_time_wei
    patch_dims: { time: 5, lat: 120, lon: 120}
    crop: {time: 0, lat: 10, lon: 10}
    offset: 1
  optim_weight1: 
    _target_: src.utils.get_linear_time_wei
    patch_dims: ${datamodule.xrds_kw.patch_dims}
    crop: {time: 0, lat: 10, lon: 10}
    offset: 1
  optim_weight2:
    _target_: src.utils.get_linear_time_wei
    patch_dims: { time: 5, lat: 120, lon: 120}
    crop: {time: 0, lat: 10, lon: 10}
    offset: 1
  solver: 
    _target_: contrib.IMT.SPDE.solver.GradSolver_Lgv
    aug_state: True
    n_step: 5
    lr_grad: 1e3
    nll: 
      _target_: contrib.IMT.SPDE.models_spde.NLL
      shape_data: 
        - 5
        - 120
        - 120
      pow: 1
      spde_type: "adv_diff"
      st_lag:
        - 1
        - 1
        - 1
      scheme: FUDM1
    nlpobs: 
      _target_: contrib.IMT.SPDE.models_spde.NLpObs
    obs_cost:
      _target_: src.models.BaseObsCost
    grad_mod: 
      _target_: src.models.ConvLstmGradModel
      dim_in: 45 #(5*9)
      dim_hidden: 244
    unet_prior: False
  solver2:
    _target_: src.models.GradSolver
    n_step: 15
    lr_grad: 1e3
    prior_cost:
      _target_: src.models.BilinAEPriorCost
      dim_in: ${datamodule.xrds_kw.patch_dims.time}
      dim_hidden: 64
      bilin_quad: False
      # bilin_quad: True
      downsamp: 2
    obs_cost:
      _target_: src.models.BaseObsCost
    grad_mod:
      _target_: src.models.ConvLstmGradModel
      dim_in: ${datamodule.xrds_kw.patch_dims.time}
      dim_hidden: 96
  test_metrics: ${metrics.test_metrics}
  pre_metric_fn: 
        _target_: xarray.Dataset.sel
        _partial_: True
        time: {_target_: builtins.slice, _args_: ["2020-11-25", "2020-12-31"]}
        lat: ${domain.test.lat}
        lon: ${domain.test.lon}
  n_simu: 100
  start_simu_idx: 0.
  ncfile_name: '4DVarNet_OSSE_SSH_frcst2.nc'

metrics:
  nrmse_scores: {_target_: src.utils.rmse_based_scores_from_ds, _partial_: True}
  psd_scores: {_target_: src.utils.psd_based_scores_from_ds, _partial_: True}
  get0: {_target_: operator.itemgetter, _args_: [0]}
  get1: {_target_: operator.itemgetter, _args_: [1]}
  test_metrics:
    'mu': {_target_: src.utils.pipe, _partial_: true, fns: ['${metrics.nrmse_scores}', '${metrics.get0}']}
    'sig': {_target_: src.utils.pipe, _partial_: true, fns: ['${metrics.nrmse_scores}', '${metrics.get1}']}
    'lx': {_target_: src.utils.pipe, _partial_: true, fns: ['${metrics.psd_scores}', '${metrics.get0}']}
    'lt': {_target_: src.utils.pipe, _partial_: true, fns: ['${metrics.psd_scores}', '${metrics.get1}']}

entrypoints:
  #- _target_: pytorch_lightning.seed_everything
  #  seed: 333
  - _target_: src.test.base_test
    trainer: ${trainer}
    lit_mod: ${model}
    dm: ${datamodule}
    save_dir: /Odyssey/private/m19beauc/DMI/results
    ckpt_path: /homes/m19beauc/4dvarnet-starter/ckpt/IMT/SPDE/ssh_spde_frcst2_6nadirs_glo_bigpatch.ckpt

defaults:
  - /domain: global
  - _self_

